### PR TITLE
Symfony 3 support using request_stack instead of request

### PR DESCRIPTION
**Pull request by peteward**
Getting the request directly from the container is no longer possible, you need to use the RequestStack

### CODE REVIEW

**Comment by EricReiche** [comment]
Hi,

thanks for your contribution.
I think the request stack was added in 2.4 or something, can you please adapt the minimum requirements in composer.json as well?

Thanks.

**Comment by peteward** [comment]
done.

Thanks for your work on this bundle 👍

**Comment by mente** [comment]
@EricReiche how about reviving this bundle as standalone library with credits to @antimattr?

**Comment by EricReiche** [comment]
Not quite sure what exactly you mean Alex.
It is independent, even though I guess the readme doesn't reflect that. Do you want to remove the symfony dependency?

**Comment by mente** [comment]
No, I mean "unfork" it from antimattr bundle and publish as a separate package in composer. With credits to antimattr of course.

+ backport our own changes

**Comment by EricReiche** [comment]
Done.

**Pull request merged**
